#app
server:
    port: 8080

#spring
spring:
  application:
    name: api-news-recommendation-client
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/news-recommendation?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: tester
      password: lkr.7664
      initialSize: 10
      minIdle: 10
      maxActive: 100
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      validationInterval: 60000
      validationQuery: SELECT 1

#mybatis：https://mp.baomidou.com/config
mybatis-plus:
  mapper-locations: classpath:/com/hilkr/api/news/recommendation/client/dal/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hilkr.api.news.recommendation.client.dal.model
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
#      数据库类型,默认值为未知的数据库类型 如果值为OTHER,启动时会根据数据库连接 url 获取数据库类型;如果不是OTHER则不会自动获取数据库类型
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false